# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Forge < Formula
  desc "Policy-driven git hook runner — fast, portable, no Node.js required."
  homepage "https://github.com/TerrorSquad/forge"
  version "2.1.2-rc.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/TerrorSquad/forge/releases/download/v2.1.2-rc.1/forge_2.1.2-rc.1_darwin_amd64.tar.gz"
      sha256 "559231f2902ff8847964fa143c322355032eb08e6c8830682ede242d23dc54f0"

      define_method(:install) do
        bin.install "forge"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/TerrorSquad/forge/releases/download/v2.1.2-rc.1/forge_2.1.2-rc.1_darwin_arm64.tar.gz"
      sha256 "0ff6465bb6fe42138484cb2e62a3d8645ccde947d0caf2df655a23ce168aee90"

      define_method(:install) do
        bin.install "forge"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/TerrorSquad/forge/releases/download/v2.1.2-rc.1/forge_2.1.2-rc.1_linux_amd64.tar.gz"
      sha256 "4de63725f997991564b0ca13ce2c2a1fd3a30b7738ccb6a59565bbe87bc901f6"
      define_method(:install) do
        bin.install "forge"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/TerrorSquad/forge/releases/download/v2.1.2-rc.1/forge_2.1.2-rc.1_linux_arm64.tar.gz"
      sha256 "5b597a3a17fe9a609f190e4f32613fe40bf8a2ac52b6600c1c0dfc93bfb13ee2"
      define_method(:install) do
        bin.install "forge"
      end
    end
  end

  test do
    system "#{bin}/forge", "version"
  end
end
