# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ForgeGit < Formula
  desc "Policy-driven git hook runner — fast, portable, no Node.js required."
  homepage "https://github.com/TerrorSquad/forge"
  version "1.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/TerrorSquad/forge/releases/download/v1.2.1/forge_1.2.1_darwin_amd64.tar.gz"
      sha256 "383ce7bef0bf6a0786fd3103ae6dec6d1912f40fd8c488d1fbb711e112735d49"

      define_method(:install) do
        bin.install "forge"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/TerrorSquad/forge/releases/download/v1.2.1/forge_1.2.1_darwin_arm64.tar.gz"
      sha256 "63201e10c80e508bdb7ca069bc72aaf66f27d63dcf50310c5fb2fcae47e26185"

      define_method(:install) do
        bin.install "forge"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/TerrorSquad/forge/releases/download/v1.2.1/forge_1.2.1_linux_amd64.tar.gz"
      sha256 "4d88251513130028a12bd45a05ad0a16da430a9ad2d90069e0bde8525d26bc82"
      define_method(:install) do
        bin.install "forge"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/TerrorSquad/forge/releases/download/v1.2.1/forge_1.2.1_linux_arm64.tar.gz"
      sha256 "8d0c6e3fb872e43396b53ecc208a635f348345b59aa0b27aef388b4759e52096"
      define_method(:install) do
        bin.install "forge"
      end
    end
  end

  test do
    system "#{bin}/forge", "version"
  end
end
