# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ForgeGit < Formula
  desc "Policy-driven git hook runner — fast, portable, no Node.js required."
  homepage "https://github.com/TerrorSquad/forge"
  version "2.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/TerrorSquad/forge/releases/download/v2.0.0/forge_2.0.0_darwin_amd64.tar.gz"
      sha256 "70e72a37349348f618aba6d3a47a009ebf3aedd9adf289b0d550dde11a6e3dc5"

      define_method(:install) do
        bin.install "forge"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/TerrorSquad/forge/releases/download/v2.0.0/forge_2.0.0_darwin_arm64.tar.gz"
      sha256 "fc663ba32bda85135ab5c26e09f9d3d55653d4e10f2cd32bbc912981c6cff0d3"

      define_method(:install) do
        bin.install "forge"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/TerrorSquad/forge/releases/download/v2.0.0/forge_2.0.0_linux_amd64.tar.gz"
      sha256 "4cbe31554b47fa8ef457e85a492efba1431e1eeca09884c5a133e9720ce93196"
      define_method(:install) do
        bin.install "forge"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/TerrorSquad/forge/releases/download/v2.0.0/forge_2.0.0_linux_arm64.tar.gz"
      sha256 "ab0236d2b27005aed9b1ce1fe74cf6ed98994653fb143d7cb01329f9ccfc4754"
      define_method(:install) do
        bin.install "forge"
      end
    end
  end

  test do
    system "#{bin}/forge", "version"
  end
end
