# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ForgeGit < Formula
  desc "Policy-driven git hook runner — fast, portable, no Node.js required."
  homepage "https://github.com/TerrorSquad/forge"
  version "2.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/TerrorSquad/forge/releases/download/v2.1.0/forge_2.1.0_darwin_amd64.tar.gz"
      sha256 "e1aca709d2bcbb45c5f78de9ad3962e4e8fb8de9161a70159fadf6a235c2769a"

      define_method(:install) do
        bin.install "forge"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/TerrorSquad/forge/releases/download/v2.1.0/forge_2.1.0_darwin_arm64.tar.gz"
      sha256 "74bf8c4b9f1fcf282ff3d64fae1e37df56093416bb01bca08cf88650fff4bee0"

      define_method(:install) do
        bin.install "forge"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/TerrorSquad/forge/releases/download/v2.1.0/forge_2.1.0_linux_amd64.tar.gz"
      sha256 "beced3cc2907060d7fde52687ca18c510f60dbaf6f6fb13e58434c06701708f6"
      define_method(:install) do
        bin.install "forge"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/TerrorSquad/forge/releases/download/v2.1.0/forge_2.1.0_linux_arm64.tar.gz"
      sha256 "8fb934ffb2c9799d84cc6fab4cbe421a83c9f9d23cd930309f01817fa155fc84"
      define_method(:install) do
        bin.install "forge"
      end
    end
  end

  test do
    system "#{bin}/forge", "version"
  end
end
