# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Forge < Formula
  desc "Policy-driven git hook runner — fast, portable, no Node.js required."
  homepage "https://github.com/TerrorSquad/forge"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/TerrorSquad/forge/releases/download/v1.0.0/forge_1.0.0_darwin_amd64.tar.gz"
      sha256 "4b97e4afb498ff12207a5e66e7aa1015157d7b5cad02f778b62e526f12d8c263"

      define_method(:install) do
        bin.install "forge"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/TerrorSquad/forge/releases/download/v1.0.0/forge_1.0.0_darwin_arm64.tar.gz"
      sha256 "c3a719359534172c043842991e0c1fb07b90b973c2d69586923397964b6c26ef"

      define_method(:install) do
        bin.install "forge"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/TerrorSquad/forge/releases/download/v1.0.0/forge_1.0.0_linux_amd64.tar.gz"
      sha256 "cd66a4fa8e5f2436201c020b0044a82aa8be80b5df6838ebc3130fd2db3a34ef"
      define_method(:install) do
        bin.install "forge"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/TerrorSquad/forge/releases/download/v1.0.0/forge_1.0.0_linux_arm64.tar.gz"
      sha256 "f19070730f73755a76b729aba592aba7faf842d87f53dcd4ef009a8dd6c6157f"
      define_method(:install) do
        bin.install "forge"
      end
    end
  end

  test do
    system "#{bin}/forge", "version"
  end
end
