# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Forge < Formula
  desc "Policy-driven git hook runner — fast, portable, no Node.js required."
  homepage "https://github.com/TerrorSquad/forge"
  version "1.0.9"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/TerrorSquad/forge/releases/download/v1.0.9/forge_1.0.9_darwin_amd64.tar.gz"
      sha256 "7d6238cf1baa727ecb957786ebf698ae743d1162ac3d5c546be86978da66607e"

      define_method(:install) do
        bin.install "forge"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/TerrorSquad/forge/releases/download/v1.0.9/forge_1.0.9_darwin_arm64.tar.gz"
      sha256 "226109a56ea0fe8eebf81dc18146440ec441ea819b92bf667cd46f50afb72ffe"

      define_method(:install) do
        bin.install "forge"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/TerrorSquad/forge/releases/download/v1.0.9/forge_1.0.9_linux_amd64.tar.gz"
      sha256 "f419de480a5c6a55ae0b7a8247ebfcdfeb53fe9b8596602c52f30ea5fb630627"
      define_method(:install) do
        bin.install "forge"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/TerrorSquad/forge/releases/download/v1.0.9/forge_1.0.9_linux_arm64.tar.gz"
      sha256 "9228133817582fae7aed266a56db81da2248040151137e06d811c9e386885a95"
      define_method(:install) do
        bin.install "forge"
      end
    end
  end

  test do
    system "#{bin}/forge", "version"
  end
end
