# Generated by .github/workflows/release.yml. DO NOT EDIT.
class PorterSender < Formula
  desc "Air-gapped file transfer: sends a file as a QR slideshow in your terminal"
  homepage "https://porter.goranninkovic.com"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/TerrorSquad/porter/releases/download/v1.0.0/porter-sender_1.0.0_aarch64-apple-darwin.tar.gz"
      sha256 "02fb2da98d4aa7999bb0831de53253dfc7d8d89102277754a0b58838cac10047"
    end
    if Hardware::CPU.intel?
      url "https://github.com/TerrorSquad/porter/releases/download/v1.0.0/porter-sender_1.0.0_x86_64-apple-darwin.tar.gz"
      sha256 "dad3444bc5e0205a7ad801d82e7d993b5ae32805e3fa27827e77a688178c0562"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/TerrorSquad/porter/releases/download/v1.0.0/porter-sender_1.0.0_aarch64-unknown-linux-gnu.tar.gz"
      sha256 "55b0629fcf744894898952ae5edd1c0dbe339dffc41aee735e99ea35ae83411a"
    end
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/TerrorSquad/porter/releases/download/v1.0.0/porter-sender_1.0.0_x86_64-unknown-linux-gnu.tar.gz"
      sha256 "faff96e8c9c0f0f308491d91e55c6b480168ea81fa56bf490221f4141950d123"
    end
  end

  def install
    bin.install "porter-sender"
  end

  test do
    # The sender itself is a TUI and needs a real terminal, so the
    # smoke test drives `join`, which is plain file I/O. It takes
    # the transfer *directory* — the base name comes from that.
    (testpath/"demo").mkpath
    (testpath/"demo/demo.partaa").write "hello "
    (testpath/"demo/demo.partab").write "world"
    system "#{bin}/porter-sender", "join", "demo", "--output", "out.txt"
    assert_equal "hello world", (testpath/"out.txt").read
  end
end
