# Generated by .github/workflows/release.yml. DO NOT EDIT.
class PorterSender < Formula
  desc "Air-gapped file transfer: sends a file as a QR slideshow in your terminal"
  homepage "https://porter.goranninkovic.com"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/TerrorSquad/porter/releases/download/v1.1.0/porter-sender_1.1.0_aarch64-apple-darwin.tar.gz"
      sha256 "c7e2129e8c8f7c8ad725b687adda45d54e5cb2ec4b3de280b6cddab28dc212f1"
    end
    if Hardware::CPU.intel?
      url "https://github.com/TerrorSquad/porter/releases/download/v1.1.0/porter-sender_1.1.0_x86_64-apple-darwin.tar.gz"
      sha256 "50a22f663d056ea36b93ed65ed329ed812bc78e21fe87d9ab4ef94a470137329"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/TerrorSquad/porter/releases/download/v1.1.0/porter-sender_1.1.0_aarch64-unknown-linux-gnu.tar.gz"
      sha256 "f7e2babb1c3e446bed0085ccd12f7665e84abf724c2e50760cd911f81bff0c9d"
    end
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/TerrorSquad/porter/releases/download/v1.1.0/porter-sender_1.1.0_x86_64-unknown-linux-gnu.tar.gz"
      sha256 "864a6ffd34dc46095cd4be281236f4e0c31bde79f79f56fd082df2e2ac1060f5"
    end
  end

  def install
    bin.install "porter-sender"
  end

  test do
    # The sender itself is a TUI and needs a real terminal, so the
    # smoke test drives `join`, which is plain file I/O. It takes
    # the transfer *directory* — the base name comes from that.
    (testpath/"demo").mkpath
    (testpath/"demo/demo.partaa").write "hello "
    (testpath/"demo/demo.partab").write "world"
    system "#{bin}/porter-sender", "join", "demo", "--output", "out.txt"
    assert_equal "hello world", (testpath/"out.txt").read
  end
end
