# Generated by .github/workflows/release.yml. DO NOT EDIT.
class PorterSender < Formula
  desc "Air-gapped file transfer: sends a file as a QR slideshow in your terminal"
  homepage "https://porter.goranninkovic.com"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/TerrorSquad/porter/releases/download/v1.0.0/porter-sender_1.0.0_aarch64-apple-darwin.tar.gz"
      sha256 "3eecef472bfa88a5ed8228ec6e4da981c07655aa5c63f5976a9e2f30dd3f69d8"
    end
    if Hardware::CPU.intel?
      url "https://github.com/TerrorSquad/porter/releases/download/v1.0.0/porter-sender_1.0.0_x86_64-apple-darwin.tar.gz"
      sha256 "a3d5bddbcacd74b4c38c75c6825145b621dd1976a5f6a7b3509abf73e36095a0"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/TerrorSquad/porter/releases/download/v1.0.0/porter-sender_1.0.0_aarch64-unknown-linux-gnu.tar.gz"
      sha256 "3722ca55c7c891273fd210119f775b5371869a734ee3b4fb9ce149a25df1ee12"
    end
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/TerrorSquad/porter/releases/download/v1.0.0/porter-sender_1.0.0_x86_64-unknown-linux-gnu.tar.gz"
      sha256 "85e9de01fd301eb2e95bc3307cf8c1a97c84f201309c86f7ebcd61848737cd37"
    end
  end

  def install
    bin.install "porter-sender"
  end

  test do
    # The sender itself is a TUI and needs a real terminal, so the
    # smoke test drives `join`, which is plain file I/O. It takes
    # the transfer *directory* — the base name comes from that.
    (testpath/"demo").mkpath
    (testpath/"demo/demo.partaa").write "hello "
    (testpath/"demo/demo.partab").write "world"
    system "#{bin}/porter-sender", "join", "demo", "--output", "out.txt"
    assert_equal "hello world", (testpath/"out.txt").read
  end
end
